const TODO_ADD = 'TODO_ADD';
const TODO_DEL = 'TODO_DEL';
const TODO_UPD = 'TODO_UPD';
const TODO_CLEAR = 'TODO_CLEAR';
const USER_GET = 'USER_GET';
const GET_CATE_GOOD = 'GET_CATE_GOOD';
const GET_CATES = 'GET_CATES';
const ADD_GOOD = 'ADD_GOOD';
const GET_GOOD_DETAIL = 'GET_GOOD_DETAIL';
const RESET_GOOD_DETAIL = 'RESET_GOOD_DETAIL';
export {
    GET_CATE_GOOD,
    TODO_ADD,
    TODO_DEL,
    TODO_UPD,
    TODO_CLEAR,
    USER_GET,
    GET_CATES,
    ADD_GOOD,
    GET_GOOD_DETAIL,
    RESET_GOOD_DETAIL
}
